# Config parameters for largest_router:


data_path:
  query_data_train: 'llmrouter/data/example_data/defaul_query_data/default_query_train.jsonl'
  query_data_test: 'llmrouter/data/example_data/defaul_query_data/default_query_test.jsonl'
  query_embedding_data: 'llmrouter/data/example_data/default_routing_data/query_embeddings_longformer.pt'
  routing_data_train: 'llmrouter/data/example_data/default_routing_data/default_routing_train_data.jsonl'
  routing_data_test: 'llmrouter/data/example_data/default_routing_data/default_routing_test_data.jsonl'
  llm_data: 'llmrouter/data/example_data/default_llm_candidates/default_llm.json'
  llm_embedding_data: 'llmrouter/data/example_data/default_llm_candidates/default_llm_embeddings.json'

metric:
  weights:
    performance: 1
    cost: 0
    llm_judge: 0




