# Automix Router configuration (train)

data_path:
  prepared_data: "data/automix/router_automix_llamapair_ver_outputs.jsonl"
  output_dir: "data/automix"
  conversion:
    default_data_dir: "data/default_data"
    train_file: "default_routing_train_data.jsonl"
    test_file: "default_routing_test_data.jsonl"
    train_output_file: "router_train_data_nq.json"
    test_output_file: "router_test_data_nq.json"
    merged_file: "train_test_nq_split.jsonl"

model_path:
  engine_small: "meta/llama-3.1-8b-instruct"
  engine_large: "meta/llama-3.1-70b-instruct"

hparam:
  routing_method: "POMDP"
  num_bins: 8
  columns:
    slm: "llama13b_f1"
    llm: "llama70b_f1"
    verifier: "p_ver_13b"
  costs:
    small_model: 1
    large_model: 50
    verifier: 1

train_param:
  device: "cpu"
  verbose: true
  num_samples: 2

display:
  separator_width: 70
  precision:
    ibc_lift: 4
    performance: 4
    cost: 2
    percentage: 1
